CREATE TABLE REVIEW(
	review_num NUMBER,
	restaurant_num NUMBER,
	member_nickname VARCHAR2(50),
	review VARCHAR2(3000),
	review_ration NUMBER,
	review_report CHAR,
	review_upload_date DATE,
	CONSTRAINT REVIEW_PK PRIMARY KEY(review_num),
	CONSTRAINT REVIEW_FK_1 FOREIGN KEY(restaurant_num) REFERENCES RESTAURANT(restaurant_num),
	CONSTRAINT REVIEW_FK_2 FOREIGN KEY(member_nickname) REFERENCES "MEMBER"(member_nickname)
);

CREATE SEQUENCE REVIEW_SEQ;

CREATE TABLE BOOKMARK(
   BOOKMARK_NUM NUMBER,
   MEMBER_ID VARCHAR2(50),
   RESTAURANT_NUM NUMBER,
   CONSTRAINT BOOKMARK_FK FOREIGN KEY(MEMBER_ID) REFERENCES "MEMBER"(MEMBER_ID),
   CONSTRAINT BOOKMARK_FK2 FOREIGN KEY(RESTAURANT_NUM) REFERENCES RESTAURANT(RESTAURANT_NUM)
);

CREATE SEQUENCE BOOKMARK_SEQ;

DROP TABLE BOOKMARK;

CREATE TABLE MENU_LIST(
	restaurant_num NUMBER,
	menu VARCHAR2(30),
	price VARCHAR2(30),
	CONSTRAINT MENU_LIST_FK FOREIGN KEY(restaurant_num) REFERENCES RESTAURANT(restaurant_num)
);

CREATE TABLE PICTURE(
   REVIEW_NUM NUMBER,
   PICTURE_NAME VARCHAR2(200),
   CONSTRAINT PICTURE_FK FOREIGN KEY(REVIEW_NUM) REFERENCES REVIEW(REVIEW_NUM),
   CONSTRAINT PICTURE_PK PRIMARY KEY(PICTURE_NAME)  
);













